version: '3.9'

services:
  database:
    image: mysql
    container_name: yachay-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlycourses
      MYSQL_USER: yachay-admin
      MYSQL_PASSWORD: yachay-password
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql

  api:
    image: yachay-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: yachay-backend-dev
    ports:
      - 3001:3000
    depends_on:
      - database
    command: bash -c 'while !</dev/tcp/database/3306; do sleep 1; done; yarn dev'
